development:
  adapter: postgresql
  encoding: unicode
  database: demo-sso-client_development
  pool: 5
  username: gambala
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: demo-sso-client_test
  pool: 5
  username: gambala
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: demo-sso-client_production
  pool: 5
  username: gambala
  password:
